apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ur-app
  name: ur-app
spec:
  containers:
  - image: nginx
    name: my-app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
